name: Test run


on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

jobs:
  tests:
    name: Test run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All active versions.
        python-version: ["3.10", "3.9", "3.8", "3.7"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        id: setup_python
      # Just run the script without the required `--type` option to check if
      # there's any compile-time error.
      - uses: gh640/command-result-action@v1
        with:
          command: ./gh-repo-list
        id: run_script
      - name: Check status
        if: ${{ steps.run_script.outputs.exitCode != 2 }}
        run: |
          echo ${{ steps.run_script.outputs.stderr }}
          exit 1
